CMS_HOST: studio.local.openedx.io
CMS_OAUTH2_SECRET: NJ0c8OiEMLSvvFYEsTsjHFJq
CONTACT_EMAIL: contact@local.openedx.io
ENABLE_HTTPS: false
ID: Mm2pKmY5XB39of8T5OowOiEc
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEAikCw6bBSaY7geHs8SLicHHDO39eOGbfghjadWCD4hADmeeZy

  qj8h3y4GnVjcH91FvIG7kaKk76mIUTfNvxRrgetFI4rseAU9OahuxS6dNY3G+Fke

  dSTyNoikhuzHPPuA0f2fSi3aeuk80hkncZG5MlGS8hPAxIcmcn1VafGlnTA9LsUQ

  J47luozl6qH7/4CYj+raxpq2y+WEZC6fKK9X/y8NT3wXkY5yBMkBPmEecel2lJn5

  sQbyy8SD55Dj0SHZMCqklEEdN5V2Wi41Gt23OJOXBuK3LwM3M9a1rpvitboShSyG

  CIYUgkLvpDdSCoCYKNUdQrNk7848u07O+HchYwIDAQABAoIBAAJc2KklukLTjkKA

  2KblgMV7qA1rQaJu4gdpJ4c6CQU4frfWmF8QdSO7RaGqwxhIT8jI7suuW+M8onfA

  3GNHlg7CVowk86WZcVJq7nmwMj+YDK5x13NpDjqgWy9zHHSOV8U+8Fn0LqerFL8C

  bwoh02hovHomnES/ioiqW6tT1eC5y+OQMUA8NTw/UoWqXlhwjLAaOKibAukm/ecP

  +c5vPMECojoAuUkIe+yKkQxz6n7Eis8hOLQZrnFjd3VBrblQtYt+UsDQ5FQ/FRV+

  sI1t9xqWKNNrJl76O1who468ztnE1yIKktzNZ/s7jFyj8EdNSFid/ewPsIzJyozb

  ctoMJAECgYEAuVqBQsO4FCVKpkjdfqhZbVOtS1iJ7Bcbgfz/06QbkHgBllwHhken

  APsR779pEfUUOhQOSgP0IdWIRyBI8vKCjWmempfmCBvPWwBb72ijUnYI9mEphFWy

  /xrmeWcDw0VRbk/YtZVt9k7uY7MnFdiJl//j3+qbufd9skuziTCbXrECgYEAvvJq

  7jTgiioo7gjg1HhR4fGEs1rw5wL7mMppHFaf2cHU9BAJwkIvc4vjgUNR46VIE28q

  z1+6dqj/s3hkhEyx151vLsECIpAFzYEv+ciCgA/3j9RbiE40QZ1IE/cNs+Dvv+R6

  7AVRifCx5X+fkWW46N5ZzVT7L26i+kmp97l1zlMCgYB4r6Vag3VoKJ/iha8yuQsB

  VGqRlKS5RJJ0oPcyJriL6Jef/2wm0qC60r9rC4auWpVA+64SI2DiZtbE+RCGn8DB

  svPCVQVCYlkxN5qk18z/9DsBsWIG+IYD9M/8XEbm7kuHOBYypYljxyERaaUZZFSy

  07rcITYkcDE31nKf8TY5AQKBgAEAlL8bV/JhtkVJlqSG3ScqdV/bolgUE+4BYfvc

  GIq0EcIWM3bpkgYxPch36f4f5/jyJG9iOUBWMsFmaGCpZmWTVfoQ2UoFJ4KkovPU

  sZqqesoueyyD/JI7mR1Btriy/Y8sS9jhTkRDFyv1N4kz13yhbic9wvPEyOY3bMT4

  HD4xAoGAQ7NfzhAQQOuo8htxGGaD7Ag74Z2OirGDTHtjf87uXlNXV83mIRYwaj1S

  PZdIdIg/iA0E2ztOEJ91+aLE3Beb8OSVgshJ2xhPVXRLHI8mleZHfugPEcU8g96x

  HeKt0Vgp56+9JKg9BBjye+WS8oNcZ3wdmosoOOORmguZB+7VPx0=

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.openedx.io
MEILISEARCH_API_KEY: 025184ffa2d8e13b26b14d70b407e4dab0b5d9ad5c8e0772049358fe4f45360d
MEILISEARCH_API_KEY_UID: 2b18ba76-66f7-4dec-a6b3-f2d7faab6881
MEILISEARCH_MASTER_KEY: WWExBoOp24qz2OlNiOmr1A0M
MYSQL_ROOT_PASSWORD: CAPlVi1R
OPENEDX_MYSQL_PASSWORD: keidf5Yy
OPENEDX_SECRET_KEY: nqhL4uaoPazhVi5J3mzdBaeU
PLATFORM_NAME: My Open edX
PLUGINS:
- mfe
- indigo
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
